# Generated by Django 4.2 on 2023-06-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_mahsulot_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='yetkazish',
            field=models.CharField(default='3 kun', max_length=30),
            preserve_default=False,
        ),
    ]
