# Generated by Django 4.2 on 2023-06-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_mahsulot_yetkazish'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='mavjud',
            field=models.BooleanField(default=True),
        ),
    ]
