# Generated by Django 4.2 on 2023-06-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0005_izoh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izoh',
            name='sana',
            field=models.DateField(auto_now_add=True),
        ),
    ]
